# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-08 03:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='password',
            new_name='password1',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='username',
            new_name='username1',
        ),
    ]
