# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-08 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_auto_20200408_1135'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserInfo',
            new_name='UsersInfo',
        ),
        migrations.RenameField(
            model_name='usersinfo',
            old_name='password1',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='usersinfo',
            old_name='username1',
            new_name='username',
        ),
    ]
