# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-08 03:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_auto_20200408_1137'),
    ]

    operations = [
        migrations.CreateModel(
            name='History_apk',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apk_name', models.CharField(max_length=1000)),
                ('apk_version', models.CharField(max_length=100)),
            ],
        ),
    ]
