# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-08 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_history_apk'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_apk',
            name='apk_addr',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history_apk',
            name='apk_size',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='history_apk',
            name='updatetime',
            field=models.TimeField(null=True),
        ),
    ]
