# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-08 06:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_auto_20200408_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_apk',
            name='updatetime',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
