# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-08 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_auto_20200408_1425'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_apk',
            name='apk_addr',
        ),
        migrations.AddField(
            model_name='history_apk',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='e://apk'),
        ),
    ]
