# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-08 06:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_auto_20200408_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history_apk',
            old_name='img',
            new_name='apk_addr',
        ),
    ]
