# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-08 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0008_auto_20200408_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_apk',
            name='updatetime',
        ),
        migrations.AddField(
            model_name='history_apk',
            name='createtime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
