# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-09 02:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0009_auto_20200408_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history_apk',
            name='apk_addr',
            field=models.ImageField(null=True, upload_to='e://apk'),
        ),
    ]
