# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-09 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0011_auto_20200409_1111'),
    ]

    operations = [
        migrations.AddField(
            model_name='history_apk',
            name='apk_addrs',
            field=models.ImageField(null=True, upload_to='apk'),
        ),
    ]
