# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-09 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0012_history_apk_apk_addrs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history_apk',
            name='apk_addrs',
        ),
    ]
