# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-10 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0013_remove_history_apk_apk_addrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='devices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_brand', models.CharField(max_length=100, null=True)),
                ('device_model', models.CharField(max_length=100, null=True)),
                ('device_size', models.CharField(max_length=100, null=True)),
                ('device_cpu', models.CharField(max_length=100, null=True)),
                ('device_sdk', models.CharField(max_length=100, null=True)),
                ('status', models.IntegerField(default=0, max_length=100)),
                ('createtime', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
