# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2020-04-10 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_devices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devices',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
